#!/bin/bash

UR_DIR=/ur

if [ $# -eq 1 ]; then
    echo "ur $1 [ build | train ]"
elif [ $# -eq 2 ]; then
    if [ -d $UR_DIR ]; then
        if [ "$2" == "build" ]; then
            if [ -d ${UR_DIR}/$1 ]; then
                echo "build $1"
                cd $UR_DIR/$1 && pio build --verbose
            else
                echo "Not a directory ${UR_DIR}/${1}"
            fi
        elif [ "$2" == "train" ]; then
            if [ -d ${UR_DIR}/vendor ]; then
                echo "train $1"
                cd $UR_DIR/$1 && pio train -- --driver-memory 8g --executor-memory 8g
            else
                echo "Not a directory ${UR_DIR}/${1}"
            fi
        else
            echo "ur $1 [ build | train ]"
        fi
    else
        echo "Not a directory ${UR_DIR}"
    fi
else
    echo "ur [ vendor ] [ build | train ]"
fi